name: paper_convert
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4=4.11.1
  - black=23.3.0
  - cairo=1.16.0
  - cssutils=2.6.0
  - lxml=4.9.1
  - numpy=1.23.3
  - pandoc=2.19.2
  - pdf2svg=0.2.3
  - pillow=9.2.0
  - pip=22.3.1
  - pybtex=0.24.0
  - pypandoc=1.10
  - python=3.10.6
  - pip:
    - mammoth==1.5.0
