name: paper_convert
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4=4.10.0
  - cairo=1.16.0
  - cssutils=2.3.0
  - lxml=4.7.1
  - numpy=1.21.2
  - pandoc=2.12
  - pdf2svg=0.2.3
  - pillow=8.4.0
  - pip=21.2.4
  - pybtex=0.24.0
  - pypandoc=1.6.3
  - python=3.9.7
  - pip:
    - mammoth==1.4.18
